services:
  flask:
    build: .
    command: flask run --host=0.0.0.0 --port=8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - savannah_db
    networks:
      - savannah_network
    environment:
      - FLASK_DEBUG=1
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@savannah_db:5432/${POSTGRES_DB}

  savannah_db:
    image: postgres:13
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - savannah_network

volumes:
  postgres_data:

networks:
  savannah_network:
    driver: bridge
