name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Caching Python packages
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Setting up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  

      # Creating virtual environment
      - name: Create Virtual Environment
        run: python3 -m venv venv
        working-directory: ./backend

      # Activating the virtual environment and installing backend dependencies
      - name: Install backend dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt  
        working-directory: ./backend

      # Setting up DATABASE_URL from secrets
      - name: Set up DATABASE_URL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      # Debugging step to check DATABASE_URL
      - name: Check DATABASE_URL
        run: |
          echo "Checking DATABASE_URL..."
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL is not set!"
            exit 1
          else
            echo "DATABASE_URL is set."
          fi

      # Running backend tests
      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest tests/ --doctest-modules -q --disable-warnings
        working-directory: ./backend  

      # Deployment step (only if all tests pass)
      - name: Deploy to Production
        if: ${{ success() }}
        run: |
          echo "Deploying to production..."

      # Notification on failure
      - name: Notify on Failure
        if: ${{ failure() }}
        run: |
          echo "Build failed! Sending notification..."