name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

        - name: Install dependencies with Yarn
        run: yarn install

      - name: Run tests with Yarn
        run: yarn test

      - name: Deploy
        if: success() 
        run: |
          echo "Deploying to production..."
